name: Build & Push image to docker hub

on:
  workflow_dispatch:
             branches:
               - "main"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image

      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "meshpotato" --password-stdin
        docker image build -t meshpotato/repository:latest .
        docker push meshpotato/repository:latest
